---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jenkins-config
  namespace: {{ .Release.Namespace }}
data:
  jenkins.yaml: |
        jenkins:
          numExecutors: 2
          clouds:
          - kubernetes:
              containerCapStr: "10"
              maxRequestsPerHostStr: "32"
              jenkinsUrl: "http://jenkins:8080"
              name: "kubernetes"
              namespace: {{ .Release.Namespace }}
              skipTlsVerify: true
        credentials:
          system:
            domainCredentials:
            - credentials:
              - usernamePassword:
                  description: "Githubuser"
                  id: "some_randome"
                  password: "123qweasdASD"
                  scope: GLOBAL
                  username: "git_hub_user"
        unclassified:
          location:
            adminAddress: {{ .Values.adminAddress | quote }}
            url: {{ .Values.externalUrl | quote }}
          shell:
            shell: "/bin/bash"
